language: python
sudo: required
dist: trusty
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y python-clang-3.8 libclang1-3.8
    - ln -s /usr/lib/python2.7/dist-packages/clang
    - ln -s /usr/lib/llvm-3.8/lib/libclang-3.8.so.1 libclang-3.8.so
    - ln -s /usr/lib/llvm-3.8/lib/libclang.so.1 libclang.so
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - coverage run setup.py test
    - coverage report --show-missing
after_success:
    - coveralls
